# Site settings
title: Coda
header-img: img/home-bg.jpg
email: yowonyoon@gmail.com
description: "A blog about composing and coding"
baseurl: ""
url: "http://MrMonsk.github.io"
twitter_username: yowonyoon
github_username:  MrMonsk


# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json"]
port: 3000
host: 0.0.0.0
gems: [jekyll-paginate]